import type { Inspection } from '../lib/api';
import { fmtDate } from '../lib/api';
import { Scale } from 'lucide-react';

export default function ReportDoc({
  inspection, reportNo, generatedBy,
}: {
  inspection: Inspection;
  reportNo: string;
  generatedBy: string;
}) {
  const res = inspection.rule_results || [];
  const fails = res.filter((r) => r.status === 'FAIL');
  const reviews = res.filter((r) => r.status === 'NEEDS REVIEW');
  const passes = res.filter((r) => r.status === 'PASS');
  return (
    <div id="report-doc" className="bg-white text-slate-800">
      <div className="border-b-4 border-double border-navy pb-4 text-center">
        <div className="flex items-center justify-center gap-2">
          <Scale size={20} className="text-navy" />
          <p className="text-[11px] font-bold uppercase tracking-[0.2em] text-navy">Department of Consumer Affairs · Legal Metrology</p>
        </div>
        <h2 className="mt-1 font-display text-2xl font-semibold text-ink">Inspection Report — Packaged Commodity</h2>
        <p className="mt-1 text-xs text-slate-500">Under the Legal Metrology Act, 2009 and the Legal Metrology (Packaged Commodities) Rules, 2011</p>
      </div>
      <div className="grid grid-cols-2 gap-x-8 gap-y-1.5 py-4 text-[13px] sm:grid-cols-4">
        {[['Report No.', reportNo], ['Inspection ID', inspection.inspection_id], ['Date & Time', fmtDate(inspection.created_at)], ['Inspector', inspection.inspector], ['Compliance Score', `${inspection.score} / 100 (${inspection.risk} risk)`], ['Verdict', inspection.status], ['Decision', inspection.decision], ['Generated by', generatedBy]].map(([k, v]) => (
          <div key={k}><p className="text-[10px] font-bold uppercase tracking-widest text-slate-400">{k}</p><p className="font-semibold text-ink">{v}</p></div>
        ))}
      </div>
      <h3 className="bg-paper px-3 py-1.5 text-[11px] font-bold uppercase tracking-[0.18em] text-navy">A · Product & responsible person</h3>
      <table className="w-full text-[13px]">
        <tbody className="divide-y divide-slate-100">
          {[['Commodity', inspection.product_name], ['Category', inspection.category], ['Manufacturer / Packer / Importer', inspection.manufacturer], ['Address', inspection.address], ['Net quantity', inspection.net_quantity], ['MRP', inspection.mrp], ['Mfg / Pkd / Import', inspection.mfg_info], ['Country of origin', inspection.country_origin], ['Consumer care', inspection.consumer_care]].map(([k, v]) => (
            <tr key={k}><td className="w-56 py-1.5 pr-4 font-semibold text-slate-500">{k}</td><td className="py-1.5 text-ink">{v || '—'}</td></tr>
          ))}
        </tbody>
      </table>
      <h3 className="mt-4 bg-paper px-3 py-1.5 text-[11px] font-bold uppercase tracking-[0.18em] text-navy">B · Compliance summary — {passes.length} passed · {fails.length} failed · {reviews.length} for review</h3>
      <table className="mt-1 w-full text-[12.5px]">
        <thead><tr className="border-b border-slate-200 text-left text-[10px] uppercase tracking-widest text-slate-400"><th className="py-1.5">Rule</th><th>Detected</th><th>Status</th><th>Explanation</th></tr></thead>
        <tbody className="divide-y divide-slate-100">
          {res.map((r) => (
            <tr key={r.ruleId} className="align-top">
              <td className="py-1.5 pr-2 font-semibold">{r.ruleId} · {r.title}</td>
              <td className="py-1.5 pr-2">“{r.detected}”</td>
              <td className="py-1.5 pr-2 font-bold">{r.status}</td>
              <td className="py-1.5 text-slate-600">{r.explanation}</td>
            </tr>
          ))}
        </tbody>
      </table>
      {fails.length > 0 && (
        <div className="mt-4">
          <h3 className="bg-paper px-3 py-1.5 text-[11px] font-bold uppercase tracking-[0.18em] text-navy">C · Violations & remedial direction</h3>
          <ul className="mt-1 list-disc space-y-1 pl-6 text-[13px] text-slate-700">
            {fails.map((f) => (
              <li key={f.ruleId}><strong>{f.ruleId} — {f.title}:</strong> {f.explanation} Rectify the declaration, re-label the affected batch and produce corrected packs for re-inspection. Liability under Section 36 of the LM Act, 2009 may apply.</li>
            ))}
          </ul>
        </div>
      )}
      <div className="mt-4">
        <h3 className="bg-paper px-3 py-1.5 text-[11px] font-bold uppercase tracking-[0.18em] text-navy">D · Inspector's decision</h3>
        <p className="mt-1 text-[13px]"><strong>{inspection.decision}</strong>{inspection.decision_note ? ` — ${inspection.decision_note}` : ''}</p>
      </div>
      <div className="mt-8 grid grid-cols-2 gap-8 text-[13px]">
        <div><div className="h-10 border-b border-slate-300" /><p className="mt-1 font-semibold">Signature of Inspector</p><p className="text-xs text-slate-500">{inspection.inspector} · Date</p></div>
        <div><div className="h-10 border-b border-slate-300" /><p className="mt-1 font-semibold">Seal / Counter-signature</p><p className="text-xs text-slate-500">Controlling Officer · Date</p></div>
      </div>
      <p className="mt-6 border-t border-slate-200 pt-3 text-[11px] leading-relaxed text-slate-400">Compliance fingerprint {inspection.fingerprint || '—'}{inspection.prev_inspection_id ? ` · Linked to previous inspection ${inspection.prev_inspection_id}` : ''} · Engine LMPC-Engine v2.3 (PCR 2011 incl. 2026 e-commerce amendments) · This is a system-generated inspection record. The statutory text of the Act and Rules prevails.</p>
    </div>
  );
}
